import type { QuoteCategory } from "@prisma/client";

export const GOALS = [
  { slug: "general-wellness", label: "General wellness", icon: "🌿", sortOrder: 1 },
  { slug: "daily-habit", label: "Build a daily habit", icon: "📆", sortOrder: 2 },
  { slug: "energy", label: "Energy", icon: "⚡", sortOrder: 3 },
  { slug: "digestion", label: "Digestion", icon: "🫄", sortOrder: 4 },
  { slug: "healthy-weight", label: "Healthy weight journey", icon: "💧", sortOrder: 5 },
  { slug: "experimenting", label: "Experimenting with cayenne", icon: "🧪", sortOrder: 6 },
  { slug: "other", label: "Other", icon: "✨", sortOrder: 7 },
];

export const CHALLENGES = [
  {
    slug: "7-day-kickstart",
    title: "7-Day Kickstart",
    description: "One week. One small habit. A good place to find your footing.",
    durationDays: 7,
    sortOrder: 1,
    isPremium: false,
  },
  {
    slug: "14-day-heat-check",
    title: "14-Day Heat Check",
    description: "Two weeks in and you'll know whether this routine fits your life.",
    durationDays: 14,
    sortOrder: 2,
    isPremium: true,
  },
  {
    slug: "30-day-hot-streak",
    title: "30-Day Hot Streak",
    description: "A full month of showing up. This is where a habit stops feeling new.",
    durationDays: 30,
    sortOrder: 3,
    isPremium: true,
  },
  {
    slug: "60-day-fire-builder",
    title: "60-Day Fire Builder",
    description: "Two months of steady heat. Built one ordinary day at a time.",
    durationDays: 60,
    sortOrder: 4,
    isPremium: true,
  },
  {
    slug: "90-day-cayenne-challenge",
    title: "90-Day Cayenne Challenge",
    description: "The long one. Ninety days of keeping your own promise.",
    durationDays: 90,
    sortOrder: 5,
    isPremium: true,
  },
];

export const ACHIEVEMENTS = [
  { slug: "first-spark", title: "First Spark", description: "Log your first day.", kind: "FIRST_ENTRY" as const, threshold: 1, tier: 1, sortOrder: 1 },
  { slug: "warming-up", title: "Warming Up", description: "Reach a 3-day streak.", kind: "STREAK" as const, threshold: 3, tier: 1, sortOrder: 2 },
  { slug: "getting-spicy", title: "Getting Spicy", description: "Reach a 7-day streak.", kind: "STREAK" as const, threshold: 7, tier: 2, sortOrder: 3 },
  { slug: "feel-the-heat", title: "Feel the Heat", description: "Reach a 14-day streak.", kind: "STREAK" as const, threshold: 14, tier: 2, sortOrder: 4 },
  { slug: "red-hot", title: "Red Hot", description: "Reach a 30-day streak.", kind: "STREAK" as const, threshold: 30, tier: 3, sortOrder: 5 },
  { slug: "seriously-spicy", title: "Seriously Spicy", description: "Reach a 60-day streak.", kind: "STREAK" as const, threshold: 60, tier: 3, sortOrder: 6 },
  { slug: "pepper-pro", title: "Pepper Pro", description: "Reach a 90-day streak.", kind: "STREAK" as const, threshold: 90, tier: 4, sortOrder: 7 },
  { slug: "on-fire", title: "On Fire", description: "Reach a 180-day streak.", kind: "STREAK" as const, threshold: 180, tier: 4, sortOrder: 8 },
  { slug: "cayenne-legend", title: "Cayenne Legend", description: "Reach a 365-day streak.", kind: "STREAK" as const, threshold: 365, tier: 5, sortOrder: 9 },
  { slug: "variety-pack", title: "Variety Pack", description: "Log cayenne using 5 different methods.", kind: "METHOD_VARIETY" as const, threshold: 5, tier: 2, sortOrder: 10 },
  { slug: "early-bird", title: "Early Bird", description: "Log before 9 AM, 10 times.", kind: "EARLY_BIRD" as const, threshold: 10, tier: 2, sortOrder: 11 },
  { slug: "consistency-crown", title: "Consistency Crown", description: "Log 30 days in a single calendar month.", kind: "MONTH_DAYS" as const, threshold: 30, tier: 4, sortOrder: 12 },
  { slug: "recipe-book", title: "Recipe Book", description: "Save 10 recipes.", kind: "RECIPES_SAVED" as const, threshold: 10, tier: 2, sortOrder: 13 },
  { slug: "century", title: "Century Club", description: "Log 100 total days.", kind: "TOTAL_DAYS" as const, threshold: 100, tier: 3, sortOrder: 14 },
];

type QuoteSeed = { text: string; category: QuoteCategory };

/** 80 original lines so the daily quote stays fresh for months. */
export const QUOTES: QuoteSeed[] = [
  // DAILY ------------------------------------------------------------------
  { text: "Small habit. Big fire.", category: "DAILY" },
  { text: "A little heat today. A stronger tomorrow.", category: "DAILY" },
  { text: "One spicy choice at a time.", category: "DAILY" },
  { text: "Today's goal: keep the flame alive.", category: "DAILY" },
  { text: "Do the small thing again.", category: "DAILY" },
  { text: "Make today another red-hot checkmark.", category: "DAILY" },
  { text: "Add some fire to your routine.", category: "DAILY" },
  { text: "Start warm. Stay warm.", category: "DAILY" },
  { text: "Ordinary day. Same good choice.", category: "DAILY" },
  { text: "A pinch now beats a plan later.", category: "DAILY" },
  { text: "Ten seconds today. That's the whole ask.", category: "DAILY" },
  { text: "Turn up the heat a little.", category: "DAILY" },
  { text: "Today counts, same as the rest.", category: "DAILY" },
  { text: "Show up small. Show up anyway.", category: "DAILY" },
  { text: "The routine works when you run it.", category: "DAILY" },
  { text: "One more day on the board.", category: "DAILY" },

  // STREAK -----------------------------------------------------------------
  { text: "Keep the streak spicy.", category: "STREAK" },
  { text: "Don't lose the fire now.", category: "STREAK" },
  { text: "Hot streaks are built one day at a time.", category: "STREAK" },
  { text: "You're on a hot streak. Protect it.", category: "STREAK" },
  { text: "Keep the fire going.", category: "STREAK" },
  { text: "Don't flake now.", category: "STREAK" },
  { text: "The flame's lit. Feed it.", category: "STREAK" },
  { text: "Every day added is a day you can't lose.", category: "STREAK" },
  { text: "Streaks don't need drama. Just tomorrow.", category: "STREAK" },
  { text: "You've got a run going. Extend it.", category: "STREAK" },
  { text: "Long streaks are short streaks that kept going.", category: "STREAK" },
  { text: "Stay steady. Stay spicy.", category: "STREAK" },
  { text: "Nothing to prove. Just one more day.", category: "STREAK" },
  { text: "The chain looks good on you.", category: "STREAK" },

  // COMEBACK ---------------------------------------------------------------
  { text: "The streak cooled off. Light it back up.", category: "COMEBACK" },
  { text: "Yesterday's gone. Today's still spicy.", category: "COMEBACK" },
  { text: "New streak. Same goal.", category: "COMEBACK" },
  { text: "Day one again is still day one done.", category: "COMEBACK" },
  { text: "Missing a day isn't quitting. Quitting is quitting.", category: "COMEBACK" },
  { text: "Embers relight faster than they look.", category: "COMEBACK" },
  { text: "You know how this works. Go again.", category: "COMEBACK" },
  { text: "The habit's still yours. Pick it back up.", category: "COMEBACK" },
  { text: "Gaps happen. Restarts count.", category: "COMEBACK" },
  { text: "No lecture. Just a match and a fresh start.", category: "COMEBACK" },
  { text: "Coming back is the hard part. You're doing it.", category: "COMEBACK" },
  { text: "Every long streak has a restart behind it.", category: "COMEBACK" },

  // MILESTONE --------------------------------------------------------------
  { text: "30 days. That's not a phase anymore.", category: "MILESTONE" },
  { text: "Look who's bringing the heat.", category: "MILESTONE" },
  { text: "Pepperformance unlocked.", category: "MILESTONE" },
  { text: "That's a real habit now.", category: "MILESTONE" },
  { text: "You built this one day at a time.", category: "MILESTONE" },
  { text: "Certified spicy.", category: "MILESTONE" },
  { text: "This is what consistency looks like.", category: "MILESTONE" },
  { text: "Big number. Small daily choices.", category: "MILESTONE" },
  { text: "Nobody handed you this streak.", category: "MILESTONE" },
  { text: "That's a milestone worth posting.", category: "MILESTONE" },
  { text: "The fire's fully caught.", category: "MILESTONE" },
  { text: "Take the win. Then take tomorrow.", category: "MILESTONE" },

  // FUNNY ------------------------------------------------------------------
  { text: "Yes, Cayenne.", category: "FUNNY" },
  { text: "You Cayenne Do It.", category: "FUNNY" },
  { text: "Spice up your résumé: extremely consistent.", category: "FUNNY" },
  { text: "Some people meditate. You seasoned.", category: "FUNNY" },
  { text: "Your habit has a little kick to it.", category: "FUNNY" },
  { text: "Peppering in some consistency.", category: "FUNNY" },
  { text: "Mild goals, hot follow-through.", category: "FUNNY" },
  { text: "Not a phase, mom. It's a routine.", category: "FUNNY" },
  { text: "Your streak is spicier than your lunch.", category: "FUNNY" },
  { text: "Doing the most, one-eighth of a teaspoon at a time.", category: "FUNNY" },
  { text: "Officially a person with a spice routine.", category: "FUNNY" },
  { text: "Warning: contains follow-through.", category: "FUNNY" },

  // ENCOURAGEMENT ----------------------------------------------------------
  { text: "You showed up. That counts.", category: "ENCOURAGEMENT" },
  { text: "Progress doesn't have to be dramatic.", category: "ENCOURAGEMENT" },
  { text: "Your future self likes what you're doing.", category: "ENCOURAGEMENT" },
  { text: "Keep going. You're cooking.", category: "ENCOURAGEMENT" },
  { text: "A little cayenne. A lot of consistency.", category: "ENCOURAGEMENT" },
  { text: "You don't need perfect. You need another day.", category: "ENCOURAGEMENT" },
  { text: "Still showing up? That's the secret.", category: "ENCOURAGEMENT" },
  { text: "Consistency is hotter than motivation.", category: "ENCOURAGEMENT" },
  { text: "Small is sustainable. Sustainable wins.", category: "ENCOURAGEMENT" },
  { text: "The boring days are the ones that build it.", category: "ENCOURAGEMENT" },
  { text: "You're further along than you were.", category: "ENCOURAGEMENT" },
  { text: "Slow is fine. Stopped is the only problem.", category: "ENCOURAGEMENT" },
  { text: "Give today the easy version of your best.", category: "ENCOURAGEMENT" },
  { text: "Nothing fancy. Just kept.", category: "ENCOURAGEMENT" },
];

type RecipeSeed = {
  slug: string;
  title: string;
  summary: string;
  category: "DRINKS" | "MEALS" | "SNACKS" | "QUICK_MIXES";
  cayenneAmount: string;
  minutes: number;
  difficulty: string;
  ingredients: string[];
  steps: string[];
};

export const RECIPES: RecipeSeed[] = [
  {
    slug: "cayenne-morning-tonic",
    title: "Cayenne Morning Tonic",
    summary: "Warm water, lemon and a pinch of heat to start the day with.",
    category: "DRINKS",
    cayenneAmount: "1/8 tsp",
    minutes: 5,
    difficulty: "Easy",
    ingredients: ["1 cup warm water", "Juice of 1/2 lemon", "1/8 tsp cayenne", "1 tsp honey (optional)"],
    steps: [
      "Warm the water until it is comfortable to sip, not boiling.",
      "Stir in the lemon juice and honey until dissolved.",
      "Add the cayenne and stir well — it likes to settle.",
      "Sip slowly and stir again halfway through.",
    ],
  },
  {
    slug: "spicy-lemon-water",
    title: "Spicy Lemon Water",
    summary: "The two-minute version. Cold, sharp and easy to repeat daily.",
    category: "DRINKS",
    cayenneAmount: "1/8 tsp",
    minutes: 2,
    difficulty: "Easy",
    ingredients: ["1 large glass cold water", "2 lemon wedges", "1/8 tsp cayenne", "Ice"],
    steps: [
      "Squeeze the lemon wedges into the glass and drop them in.",
      "Add cayenne and stir vigorously for ten seconds.",
      "Top with ice and stir once more before drinking.",
    ],
  },
  {
    slug: "cayenne-tea",
    title: "Cayenne Tea",
    summary: "Black or herbal tea with a warm finish.",
    category: "DRINKS",
    cayenneAmount: "1/8 tsp",
    minutes: 5,
    difficulty: "Easy",
    ingredients: ["1 tea bag of your choice", "1 cup hot water", "1/8 tsp cayenne", "Cinnamon stick (optional)"],
    steps: [
      "Steep the tea for three to four minutes and remove the bag.",
      "Whisk in the cayenne while the tea is still hot.",
      "Add a cinnamon stick and let it sit one more minute.",
    ],
  },
  {
    slug: "fire-cider-simple",
    title: "Fire Cider (Simple)",
    summary: "A small-batch vinegar mix you can keep in the fridge all week.",
    category: "QUICK_MIXES",
    cayenneAmount: "1/4 tsp per serving",
    minutes: 10,
    difficulty: "Easy",
    ingredients: [
      "1 cup apple cider vinegar",
      "2 tbsp grated ginger",
      "1 tbsp grated horseradish",
      "2 cloves garlic, crushed",
      "1 tsp cayenne",
      "1 tbsp honey",
    ],
    steps: [
      "Combine everything in a clean jar with a tight lid.",
      "Shake well and refrigerate.",
      "Shake before each use and pour 1 tbsp into water.",
      "Use within two weeks.",
    ],
  },
  {
    slug: "spicy-smoothie",
    title: "Spicy Mango Smoothie",
    summary: "Sweet fruit up front, gentle heat on the finish.",
    category: "DRINKS",
    cayenneAmount: "1/8 tsp",
    minutes: 5,
    difficulty: "Easy",
    ingredients: ["1 cup frozen mango", "1/2 banana", "3/4 cup orange juice", "1/8 tsp cayenne", "Squeeze of lime"],
    steps: [
      "Blend the mango, banana and juice until completely smooth.",
      "Add cayenne and lime, then pulse twice more.",
      "Taste and add a second pinch only if you want it.",
    ],
  },
  {
    slug: "cayenne-shot",
    title: "Cayenne Shot",
    summary: "Two ounces, straight down, done in seconds.",
    category: "DRINKS",
    cayenneAmount: "1/4 tsp",
    minutes: 2,
    difficulty: "Easy",
    ingredients: ["2 oz orange juice", "1/4 tsp cayenne", "1/2 tsp grated ginger", "Pinch of salt"],
    steps: [
      "Stir everything together in a small glass.",
      "Stir again right before drinking so nothing settles.",
      "Chase with water if you want to.",
    ],
  },
  {
    slug: "spiced-scrambled-eggs",
    title: "Spiced Scrambled Eggs",
    summary: "The easiest way to work cayenne into breakfast.",
    category: "MEALS",
    cayenneAmount: "1/8 tsp",
    minutes: 8,
    difficulty: "Easy",
    ingredients: ["3 eggs", "1 tbsp butter", "1/8 tsp cayenne", "Salt and pepper", "Chopped chives"],
    steps: [
      "Beat the eggs with the cayenne, salt and pepper.",
      "Melt butter over low heat and add the eggs.",
      "Stir slowly and pull them off just before they look done.",
      "Finish with chives.",
    ],
  },
  {
    slug: "cayenne-roasted-chickpeas",
    title: "Cayenne Roasted Chickpeas",
    summary: "A crunchy snack that keeps for days.",
    category: "SNACKS",
    cayenneAmount: "1/2 tsp per batch",
    minutes: 35,
    difficulty: "Easy",
    ingredients: ["1 can chickpeas, drained and dried", "1 tbsp olive oil", "1/2 tsp cayenne", "1/2 tsp smoked paprika", "Salt"],
    steps: [
      "Heat the oven to 400°F (200°C).",
      "Toss the chickpeas with oil, cayenne, paprika and salt.",
      "Roast 25–30 minutes, shaking the pan halfway.",
      "Cool completely before storing so they stay crisp.",
    ],
  },
  {
    slug: "hot-honey-drizzle",
    title: "Hot Honey Drizzle",
    summary: "Keep a jar by the stove and it ends up on everything.",
    category: "QUICK_MIXES",
    cayenneAmount: "1/2 tsp per jar",
    minutes: 5,
    difficulty: "Easy",
    ingredients: ["1/2 cup honey", "1/2 tsp cayenne", "1 tsp apple cider vinegar"],
    steps: [
      "Warm the honey gently until it pours easily.",
      "Whisk in the cayenne and vinegar.",
      "Cool and store in a sealed jar at room temperature.",
    ],
  },
  {
    slug: "cayenne-cocoa",
    title: "Cayenne Hot Cocoa",
    summary: "Dark chocolate and a slow warmth underneath it.",
    category: "DRINKS",
    cayenneAmount: "1/8 tsp",
    minutes: 8,
    difficulty: "Easy",
    ingredients: ["1 cup milk of choice", "2 tbsp cocoa powder", "1 tbsp sugar or maple syrup", "1/8 tsp cayenne", "Pinch of cinnamon"],
    steps: [
      "Warm the milk over medium-low heat.",
      "Whisk in the cocoa and sweetener until no lumps remain.",
      "Add the cayenne and cinnamon and whisk another minute.",
    ],
  },
  {
    slug: "spicy-tomato-soup",
    title: "Spicy Tomato Soup",
    summary: "A weeknight bowl with a warm edge.",
    category: "MEALS",
    cayenneAmount: "1/4 tsp per pot",
    minutes: 25,
    difficulty: "Easy",
    ingredients: ["1 can crushed tomatoes", "1 small onion, diced", "2 cloves garlic", "1 cup broth", "1/4 tsp cayenne", "Splash of cream"],
    steps: [
      "Soften the onion and garlic in a little oil.",
      "Add the tomatoes, broth and cayenne; simmer 15 minutes.",
      "Blend smooth and finish with cream.",
    ],
  },
  {
    slug: "cayenne-popcorn",
    title: "Cayenne Popcorn",
    summary: "Movie-night snack with a bit of a bite.",
    category: "SNACKS",
    cayenneAmount: "1/4 tsp per bowl",
    minutes: 6,
    difficulty: "Easy",
    ingredients: ["6 cups popped popcorn", "2 tbsp melted butter", "1/4 tsp cayenne", "1/4 tsp garlic powder", "Salt"],
    steps: [
      "Drizzle the butter over the popcorn a little at a time.",
      "Mix the cayenne, garlic powder and salt in a small bowl.",
      "Sprinkle over the popcorn, tossing between each addition.",
    ],
  },
  {
    slug: "spice-shaker-blend",
    title: "Everyday Spice Shaker",
    summary: "Mix once, then it's a shake instead of a decision.",
    category: "QUICK_MIXES",
    cayenneAmount: "About 1/8 tsp per shake",
    minutes: 5,
    difficulty: "Easy",
    ingredients: ["2 tbsp cayenne", "2 tbsp smoked paprika", "1 tbsp garlic powder", "1 tbsp onion powder", "1 tsp black pepper"],
    steps: [
      "Combine everything in a small shaker jar.",
      "Shake to blend evenly.",
      "Keep it where you cook so it actually gets used.",
    ],
  },
  {
    slug: "cayenne-avocado-toast",
    title: "Cayenne Avocado Toast",
    summary: "Thirty seconds of extra effort, noticeably better toast.",
    category: "SNACKS",
    cayenneAmount: "1/8 tsp",
    minutes: 5,
    difficulty: "Easy",
    ingredients: ["1 slice good bread", "1/2 avocado", "1/8 tsp cayenne", "Squeeze of lemon", "Flaky salt"],
    steps: [
      "Toast the bread well.",
      "Mash the avocado with lemon and salt and spread it thick.",
      "Dust the cayenne evenly across the top.",
    ],
  },
  {
    slug: "warm-cayenne-broth",
    title: "Warm Cayenne Broth",
    summary: "A savoury alternative when you don't want anything sweet.",
    category: "DRINKS",
    cayenneAmount: "1/8 tsp",
    minutes: 5,
    difficulty: "Easy",
    ingredients: ["1 cup vegetable or bone broth", "1/8 tsp cayenne", "1/2 tsp grated ginger", "Squeeze of lemon"],
    steps: [
      "Heat the broth until steaming.",
      "Stir in the cayenne and ginger.",
      "Finish with lemon and drink from a mug.",
    ],
  },
];
